version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres' 
      - 'POSTGRES_PASSWORD=password'
    networks:
      - artefatox
    ports:
      - '5432:5432'
    
networks:
  artefatox:
    driver: bridge